spring:
  datasource:
    url: jdbc:mysql://localhost:3307/stockDiscussion?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 994499
    driver-class-name: com.mysql.cj.jdbc.Driver

#spring:
#  datasource:
#    url: jdbc:mysql://my-dockertest-rds.cz8muk2o6squ.ap-northeast-2.rds.amazonaws.com:3306/blogProject
#    username: seungsu8848
#    password: 994499jun!
#    driver-class-name: com.mysql.cj.jdbc.Driver